/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import org.itson.dominio.Usuario;
import org.itson.dominio.Prestamo;
import org.itson.dominio.Libro;
import org.itson.negocio.LibroNegocio;
import org.itson.negocio.PrestamoNegocio;
import org.itson.negocio.UsuarioNegocio;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.itson.dominio.EstadoPrestamo;
/**
 *
 * @author marco
 */
public class FrmPrestarLibro extends javax.swing.JFrame {

    private PrestamoNegocio pmNegocio;
    private DefaultTableModel librosTableModel;
    private DefaultTableModel esperaTableModel;

    /**
     * Creates new form FrmPrestarLibro
     */
    public FrmPrestarLibro() throws Exception {
        initComponents();
        pmNegocio = new PrestamoNegocio();
        inicializarTablas();
        obtenerUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librosTabla = new javax.swing.JTable();
        listaUsuarios = new javax.swing.JComboBox<>();
        btnPrestar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEspera = new javax.swing.JTable();
        btnMoverLibro = new javax.swing.JButton();
        btnMover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        librosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(librosTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 480, 290));

        listaUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(listaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 120, 50));

        tablaEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaEspera);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 360, 200));

        btnMoverLibro.setText("Mover");
        btnMoverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverLibroActionPerformed(evt);
            }
        });
        jPanel1.add(btnMoverLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        btnMover.setText("Mover ");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });
        jPanel1.add(btnMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Prestar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 140, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
        try {
            UsuarioNegocio unegocio = new UsuarioNegocio();
            
           
            List<Libro> librosPrestamo = obtenerLibrosTabla(tablaEspera);
      
            // Obtener el usuario seleccionado en la lista de usuarios
            String nombreUsuario = (String) listaUsuarios.getSelectedItem();
            Usuario usuarioSeleccionado = unegocio.getUsuarioByName(nombreUsuario);

            // Verificar que se haya seleccionado un usuario
            if (usuarioSeleccionado == null) {
                mostrarAlerta("Por favor, selecciona un usuario.");
                return;
            }
            
            Prestamo prestamo = new Prestamo(librosPrestamo, usuarioSeleccionado, EstadoPrestamo.PRESTADO);
            pmNegocio.registrarPrestamo(prestamo);

        
            JOptionPane.showMessageDialog(this, "Préstamo realizado con éxito.");
            esperaTableModel.setRowCount(0);
            
        } catch (Exception ex) {
            mostrarAlerta("Error al realizar el préstamo: " + ex.getMessage());
        }
        
        this.dispose();
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnMoverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverLibroActionPerformed
        // TODO add your handling code here:
        moverFilaEntreTablas(librosTabla, esperaTableModel);
    }//GEN-LAST:event_btnMoverLibroActionPerformed

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        // TODO add your handling code here:
        moverFilaEntreTablas(tablaEspera, librosTableModel);
    }//GEN-LAST:event_btnMoverActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frm = new FrmPrincipal();
        this.dispose();
        frm.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private List<Libro> obtenerLibrosTabla(JTable tabla) throws Exception {
        LibroNegocio lnegocio = new LibroNegocio();
        List<Libro> libros = new ArrayList<>();
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {
               
            String isbn = (String) modelo.getValueAt(i, 2);     
            Libro libro = lnegocio.obtenerLibroISBN(isbn);
            libros.add(libro);
        }

        return libros;
    }
    
    public void inicializarTablas() throws Exception{
        librosTableModel = new DefaultTableModel();
        librosTableModel.addColumn("Título");
        librosTableModel.addColumn("Autor");
        librosTableModel.addColumn("ISBN");
        librosTableModel.addColumn("Estado");

        librosTabla.setModel(librosTableModel);
        obtenerLibros();
        
        esperaTableModel = new DefaultTableModel();
        esperaTableModel.addColumn("Título");
        esperaTableModel.addColumn("Autor");
        esperaTableModel.addColumn("ISBN");
        esperaTableModel.addColumn("Estado");

        tablaEspera.setModel(esperaTableModel);
    }
    
    public void obtenerLibros() throws Exception{
        LibroNegocio lbNegocio = new LibroNegocio();
        List<Libro> librosDisponibles = lbNegocio.obtenerLibrosDisponibles();
        for (Libro libro : librosDisponibles) {
            Object[] rowData = {libro.getTitulo(), libro.getAutor(), libro.getIsbn(), libro.isDisponibilidad()};
            librosTableModel.addRow(rowData);
        }
    }
    
   
    public void obtenerUsuarios() throws Exception {
        UsuarioNegocio uNegocio = new UsuarioNegocio();
        List<Usuario> usuarios = uNegocio.getAllUsuarios();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        listaUsuarios.setModel(model);

        for (Usuario usuario : usuarios) {
            model.addElement(usuario.getNombre());
        }
    }
    
    private void moverFilaEntreTablas(javax.swing.JTable tablaOrigen, DefaultTableModel modeloDestino) {
        int filaSeleccionada = tablaOrigen.getSelectedRow();
        if (filaSeleccionada == -1) {
            mostrarAlerta("Por favor, selecciona una fila para mover.");
            return;
        }

        // Obtener el modelo de la tabla de origen
        DefaultTableModel modeloOrigen = (DefaultTableModel) tablaOrigen.getModel();

        // Obtener datos de la fila seleccionada en tablaOrigen
        Vector rowData = (Vector) modeloOrigen.getDataVector().get(filaSeleccionada);

        // Agregar fila a modeloDestino
        modeloDestino.addRow(rowData);

        // Eliminar fila seleccionada de modeloOrigen
        modeloOrigen.removeRow(filaSeleccionada);
    }
    
    private void mostrarAlerta(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Alerta", JOptionPane.ERROR_MESSAGE);
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrestarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrestarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrestarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrestarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmPrestarLibro().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrmPrestarLibro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMover;
    private javax.swing.JButton btnMoverLibro;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable librosTabla;
    private javax.swing.JComboBox<String> listaUsuarios;
    private javax.swing.JTable tablaEspera;
    // End of variables declaration//GEN-END:variables
}
